### ISSUE TITLE
Using servos with Pi3

### ISSUE THREAD

**Issue by AbbasKagdi** [lipoja/AMSpi#8]
How to use this code for pan and tilt setup using 2 servos on a Raspberry Pi 3

**Comment by lipoja** [comment]
Hi I think that for servos you don't need this library at all. Because as far as I know the servo pins on the motor shield are just directly extended pins from RasPi. 

Please try google/youtub; there is a lot of tutorials on theme "how to use servos" with RasPi. And if you are able to make it work and integrate it with this library I would gladly accept your pull request with the changes. 

Thank you!

**Comment by AbbasKagdi** [comment]
Thanks for your input.
